#pragma once

enum class FractalType
{
    None,
    Mandelbrot,
    MandelbrotZM,
    Julia,
    JuliaZM,
    NewtonRaphsonMethod,
    Sinusoidal,
    Magnetic,
    Jellyfish,
    Manowar,
    ManowarJulia,
    SierpinskiTriangle,
    KochSnowflake,
    VectorSierpinskiTriangle,
    SierpinskiCarpet,
    FixedPoint1,
    FixedPoint2,
    FixedPoint3,
    FixedPoint4,
    Tricorn,
    BurningShip,
    BurningShipJulia,
    Fractory,
    Cell,
    LogisticMap,
    HenonMap,
    DoublePendulum,
    UserDefinedEscapeTime,
    UserDefinedFixedPoint,
    UserDefinedNewtonRaphson,
    ScriptFractal,
    Undefined
};
