#pragma once
#ifndef _WXCLANG
#define _WXCLANG

#ifdef wxcLANG_ENGLISH

// General
#define applyTxt "Apply"
#define okTxt "Ok"
#define yesTxt "Yes"
#define noTxt "No"
#define closeTxt "Close"
#define cancelTxt "Cancel"
#define optionsTxt "Options"
#define fileNotFoundTxt "Error: Info file not found."

// Main window
#define menuMandelbrotTxt "Mandelbrot"
#define menuMandelbrotZNTxt "MandelbrotZN"
#define menuJuliaTxt "Mandelbrot (Julia)"
#define menuJuliaZNTxt "MandelbrotZN (Julia)"
#define menuNewtonTxt "Newton"
#define menuSineTxt "Sine (Julia)"
#define menuMagnetTxt "Magnet"
#define menuJellyfishTxt "Jellyfish"
#define menuManowarTxt "Manowar"
#define menuManowarJuliaTxt "Manowar (Julia)"
#define menuSierpinskiTxt "Sierpinski Triangle"
#define menuFixedPointTxt "Fixed Point"
#define menuTricornTxt "Tricorn"
#define menuBurningShipTxt "Burning Ship"
#define menuBurningShipJuliaTxt "Burning Ship (Julia)"
#define menuFractoryTxt "Fractory"
#define menuCellTxt "Cell"
#define menuLogisticTxt "Logistic Map"
#define menuHenonMapTxt "Henon Map"
#define menuDoublePendulumTxt "Double pendulum"
#define menuUserFormComplexTxt "User Formula (Complex)"
#define menuUserFormFixedTxt "User Formula (Fixed Point)"
#define menuComplexTxt "Complex"
#define menuNumMetTxt "Numerical method"
#define menuPhysicTxt "Physic"
#define menuOtherTxt "Other"
#define menuFormulaTxt "Formula"
#define menuManualConstTxt "Manual"
#define menuSliderTxt "Slider"
#define menuEnterConstTxt "Enter Julia constant"
#define menuJuliaModeTxt "Julia mode"
#define menuShowOrbitTxt "Show orbit"
#define menuSaveImageTxt "Save image"
#define menuQuitTxt "Quit"
#define menuConsoleTxt "Console"
#define menuConsoleDescriptionTxt "Opens the command console."
#define menuManualIterTxt "Manual iterations"
#define menuIncIterTxt "Increase iterations"
#define menuDecIterTxt "Decrease iterations"
#define menuEnterUserFormTxt "Enter user formula"
#define menuFractalOptTxt "Fractal options"
#define menuPauseTxt "Pause"
#define menuRedrawTxt "Redraw"
#define menuResetTxt "Reset"
#define menuContinueTxt "Continue"
#define menuAbortTxt "Abort"
#define menuRelaunchTxt "Relaunch script"
#define menuApplyTxt applyTxt
#define menuColorOptTxt "Color options"
#define menuUserManTxt "User manual"
#define menuKeybGuideTxt "Keyboard guide"
#define menuAboutTxt "About"
#define welcomeDialogTxt "Open welcome guide"
#define menuFileTxt "File"
#define menuFractalTxt "Fractal"
#define menuIterationsTxt "Iterations"
#define menuColorTxt "Color"
#define menuToolsTxt "Tools"
#define menuHelpTxt "Help"
#define menuWelcomeTxt "Welcome to wxChaos"
#define menuAboutLegendTxt "Carlos Manuel Rodriguez y Martinez.\nEmail: fis.carlosmanuel@gmail.com\nAn open source fractal generator.\nThis program is distributed under the GPLv3 license."
#define menuSelectFileTxt "Select file name"
#define menuUsrManualError "not found"
#define menuOpenScriptFolder "Open script folder"

// ConfFractOptDialog
#define optKRealTxt "K real"
#define optKImagTxt "K imaginary"

// FractalClasses
#define fractIterationsTxt " Iterations: "

// Fractal types
#define buddhaRandPTxt "Number of buddhabrot\nrandom points:"
#define bailoutTxt "Bailout: "
#define minStepTxt "Min step: "
#define seedTxt "Seed: "
#define stabilizeTxt "Stabilize point "
#define alphaTxt "Alpha: "
#define betaTxt "Beta: "
#define th1BailoutTxt " θ1 Bailout"
#define th2BailoutTxt " θ2 Bailout"
#define valueTxt "Value: "
#define deltaTTxt "DeltaT: "
#define longitudeTxt "Longitude: "
#define gravityTxt "Gravity: "
#define relAnglesTxt " Relative angles"

// ColorFrame
#define colorAlgTxt "Color algorithm"
#define colorOptTxt optionsTxt
#define relColorTxt " Relative colors"
#define extColorTxt " Fractal color (external color)"
#define intColorTxt " Set color (internal color)"
#define orbitTrapTxt " Orbit traps"
#define smoothRenTxt " Smooth render"
#define colorVarTxt "Color variation"
#define setColorTxt "Set color"		// Color of the set.
#define redTxt "Red"
#define greenTxt "Green"
#define blueTxt "Blue"
#define redColTxt "Red: "
#define greenColTxt "Green: "
#define blueColTxt "Blue: "
#define colorStlTxt "Color styles:"
#define changeGradTxt "Change gradient"
#define paletteSizeTxt "Palette size:"
#define useGradTxt "Gradient color"
#define stdColorTxt "Gaussian Color"
#define intensityTxt "Intensity: "
#define positionTxt "Position: "
#define stdDevTxt "Standard deviation: "
#define escapeTimeTxt "Escape time"
#define gaussianIntTxt "Gaussian integer"
#define buddhabrotTxt "Buddhabrot"
#define escapeAngleTxt "Escape angle"
#define triangIneqTxt "Triangle inequality"
#define chaosMapTxt "Chaotic map"
#define lyapTxt "Lyapunov"
#define convTestTxt "Convergence test"
#define specialAlgTxt "Special algorithm"

// Color styles
#define customStyleTxt "Custom"
#define summerDayTxt "Summer day"
#define coolBlueTxt "Cool Blue"
#define hardRed "Hard Red"
#define blackWhiteTxt "Black & White"
#define pastelTxt "Pastel"
#define psychExpTxt "Psych Experience"
#define vividColTxt "Vivid colors"

// MuParserX
#define errorParserTxt "Parser error: "
#define errorFormulaTxt "Parser error: On formula "

// ConstDialog
#define realValTxt "Real value"
#define imagValTxt "Imaginary value"

// Formula Dialog
#define userFormTxt "User formula"
#define availableFuncTxt "Available functions:\n"
#define availableLabelTxt "Available functions"
#define formulaTxt "Formula"
#define bailValueTxt "Bailout value:"
#define fractTypeTxt "Fractal type:"
#define complexTypeTxt "Complex"
#define fixedPointTypeTxt "Fixed point"
#define juliaTypeTxt "Julia type"

// Fractal canvas
#define realLabelTxt "Real: "
#define imagLabelTxt "   Imaginary: "

// IterDialog
#define iterationsTxt "Iterations"

// SizeDialgoSave
#define savingTxt "Saving..."
#define renderingDotsTxt "Rendering: "
#define pauseTxt "Pause"
#define continueTxt "Continue"
#define selectSizeTxt "Select image size"
#define widthTxt "Width"
#define heightTxt "Height"

// Gradient Dialog
#define gradEditorTxt "Gradient editor"
#define gradientTxt "Gradient"
#define stopsTxt "Stops"
#define colortxt "Color: "
#define eraseTxt "Erase"


#endif
#ifdef wxcLANG_SPANISH

// General
#define applyTxt "Aplicar"
#define okTxt "Ok"
#define yesTxt "Sí"
#define noTxt "No"
#define closeTxt "Cerrar"
#define cancelTxt "Cancelar"
#define optionsTxt "Opciones"
#define fileNotFoundTxt "Error: Archivo no encontrado."

// Ventana principal
#define menuMandelbrotTxt "Mandelbrot"
#define menuMandelbrotZNTxt "MandelbrotZN"
#define menuJuliaTxt "Mandelbrot (Julia)"
#define menuJuliaZNTxt "MandelbrotZN (Julia)"
#define menuNewtonTxt "Newton"
#define menuSineTxt "Sinoidal (Julia)"
#define menuMagnetTxt "Magnetico"
#define menuJellyfishTxt "Medusa"
#define menuManowarTxt "Manowar"
#define menuManowarJuliaTxt "Manowar (Julia)"
#define menuSierpinskiTxt "Triangulo de Sierpinski"
#define menuFixedPointTxt "Punto fijo"
#define menuTricornTxt "Tricornio"
#define menuBurningShipTxt "Barco en llamas"
#define menuBurningShipJuliaTxt "Barco en llamas (Julia)"
#define menuFractoryTxt "Fractory"
#define menuCellTxt "Celula"
#define menuLogisticTxt "Mapa logístico"
#define menuHenonMapTxt "Mapa de Henón"
#define menuDoublePendulumTxt "Doble péndulo"
#define menuUserFormComplexTxt "Fórmula de usuario (compleja)"
#define menuUserFormFixedTxt "Fórmula de usuario (punto fijo)"
#define menuComplexTxt "Complejo"
#define menuNumMetTxt "Método numérico"
#define menuPhysicTxt "Físico"
#define menuOtherTxt "Otro"
#define menuFormulaTxt "Fórmula"
#define menuManualConstTxt "Manual"
#define menuSliderTxt "Deslizador"
#define menuEnterConstTxt "Introducir constante julia"
#define menuJuliaModeTxt "Modo Julia"
#define menuShowOrbitTxt "Mostar órbita"
#define menuSaveImageTxt "Guardar imagen"
#define menuQuitTxt "Salir"
#define menuConsoleTxt "Consola"
#define menuConsoleDescriptionTxt "Abre la consola de comandos."
#define menuDimCalcTxt "Calcular dimensión"
#define menuDimCalcDescriptionTxt "Ventana para calcular dimensión fractal."
#define menuDPExpTxt "Explorador DP"
#define menuDPExpDescriptionTxt "Explorador de fractales doble péndulo"
#define menuManualIterTxt "Cambiar iteraciones"
#define menuIncIterTxt "Aumentar iteraciones"
#define menuDecIterTxt "Disminuir iteraciones"
#define menuEnterUserFormTxt "Fórmula de usuario"
#define menuFractalOptTxt "Opciones del fractal"
#define menuPauseTxt "Pausa"
#define menuRedrawTxt "Redibujar"
#define menuResetTxt "Resetear"
#define menuContinueTxt "Continuar"
#define menuAbortTxt "Abortar"
#define menuRelaunchTxt "Reiniciar script"
#define menuApplyTxt applyTxt
#define menuColorOptTxt "Opciones de color"
#define menuUserManTxt "Manual de usuario"
#define menuKeybGuideTxt "Guía del programa"
#define menuAboutTxt "Acerca de wxChaos"
#define menuFileTxt "Archivo"
#define menuFractalTxt "Fractal"
#define menuIterationsTxt "Iteraciones"
#define menuColorTxt "Color"
#define menuToolsTxt "Herramientas"
#define menuHelpTxt "Ayuda"
#define menuWelcomeTxt "Bienvenido a wxChaos"
#define menuAboutLegendTxt "Carlos Manuel Rodriguez y Martinez.\nEmail: fis.carlosmanuel@gmail.com\nUn generador de fractales de código abierto.\nEste programa se ditribuye bajo la licencia GPLv3."
#define menuSelectFileTxt "Selecciona nombre de archivo"
#define menuUsrManualError "no se ha encontrado."
#define menuOpenScriptFolder "Abrir folder de scripts"

// ConfFractOptDialog
#define optKRealTxt "K real"
#define optKImagTxt "K imaginario"

// FractalClasses
#define fractIterationsTxt "Iteraciones: "

// Fractal types
#define buddhaRandPTxt "Número de aleatorios\nen buddhabrot:"
#define bailoutTxt "Escape: "
#define minStepTxt "Paso mínimo: "
#define seedTxt "Semilla: "
#define stabilizeTxt "Estabilizar punto "
#define alphaTxt "Alfa: "
#define betaTxt "Beta: "
#define th1BailoutTxt " escape th1"
#define th2BailoutTxt " escape th2"
#define valueTxt "Valor: "
#define deltaTTxt "DeltaT: "
#define longitudeTxt "Longitud: "
#define gravityTxt "Gravedad: "
#define relAnglesTxt " Ángulos relativos"

// ColorFrame
#define colorAlgTxt "Algoritmo de color"
#define colorOptTxt optionsTxt
#define relColorTxt " Colores relativos"
#define extColorTxt " Color externo"
#define intColorTxt " Color interno"
#define orbitTrapTxt " Trampas orbitales"
#define smoothRenTxt " Coloreado suave"
#define colorVarTxt "Variación de color"
#define setColorTxt "Color del fractal"		// Color of the set.
#define redTxt "Rojo"
#define greenTxt "Verde"
#define blueTxt "Azul"
#define redColTxt "Rojo: "
#define greenColTxt "Verde: "
#define blueColTxt "Azul: "
#define colorStlTxt "Estilos de color:"
#define changeGradTxt "Cambiar gradiente"
#define paletteSizeTxt "Tamaño de paleta:"
#define useGradTxt "Usar gradiente"
#define intensityTxt "Intensidad: "
#define positionTxt "Posición: "
#define stdDevTxt "Desviación estándar: "
#define stdColorTxt "Color EST"
#define escapeTimeTxt "Tiempo de escape"
#define gaussianIntTxt "Entero gaussiano"
#define buddhabrotTxt "Buddhabrot"
#define escapeAngleTxt "Ángulo de escape"
#define triangIneqTxt "Desigualdad del triángulo"
#define chaosMapTxt "Mapa caótico"
#define lyapTxt "Lyapunov"
#define convTestTxt "Test de convergencia"
#define specialAlgTxt "Algoritmo especial"

// Estilos de color
#define customStyleTxt "Personalizado"
#define summerDayTxt "Día de verano"
#define coolBlueTxt "Azul frío"
#define hardRed "Rojo fuerte"
#define blackWhiteTxt "Blanco y negro"
#define pastelTxt "Pastel"
#define psychExpTxt "Experiencia psicotrópica"
#define vividColTxt "Colores vivos"

// MuParserX
#define errorParserTxt "Error en parser: "
#define errorFormulaTxt "Error en parser: En fórmula "

// ConstDialog
#define realValTxt "Valor real"
#define imagValTxt "Valor imaginario"

// Formula Dialog
#define userFormTxt "Fórmula de usuario"
#define availableFuncTxt "Funciones disponibles:\n"
#define availableLabelTxt "Funciones disponibles"
#define formulaTxt "Fórmula"
#define bailValueTxt "Valor de escape:"
#define fractTypeTxt "Tipo de fractal:"
#define complexTypeTxt "Complejo"
#define fixedPointTypeTxt "Punto fijo"
#define juliaTypeTxt "Tipo Julia"

// Fractal canvas
#define realLabelTxt "Real: "
#define imagLabelTxt "   Imaginario: "

// IterDialog
#define iterationsTxt " Iteraciones"

// SizeDialgoSave
#define savingTxt "Guardando..."
#define renderingDotsTxt "Trazando: "
#define pauseTxt "Pausar"
#define continueTxt "Continuar"
#define selectSizeTxt "Selecciona tamaño de imagen"
#define widthTxt "Anchura"
#define heightTxt "Altura"


// Gradient Dialog
#define gradEditorTxt "Editor de gradiente"
#define gradientTxt "Gradiente"
#define stopsTxt "Puntos"
#define colortxt "Color: "
#define eraseTxt "Borrar"

#endif

#endif //_WXCLANG
